const String mainDartTemplate = r'''
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'core/app.dart';
import 'core/config/app_config.dart';
import 'core/router/app_router.dart';
import 'core/service_locator.dart';
import 'generated/l10n.dart'; // Generated by `flutter gen-l10n`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load app configuration
  await AppConfig.load();

  // Setup Dependency Injection
  await ServiceLocator.setup();

  runApp(
    MultiProvider(
      providers: AppProviders.providers,
      child: const MainApp(),
    ),
  );
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: AppRouter.router,
      title: AppConfig.appName,
      debugShowCheckedModeBanner: false,
      theme: ThemeData.light(), // Placeholder, will use actual theme
      darkTheme: ThemeData.dark(), // Placeholder, will use actual theme
      themeMode: ThemeMode.system, // Placeholder, will be managed by a ThemeProvider

      // Localization delegates
      localizationsDelegates: const [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
    );
  }
}
''';
