const String mainDartTemplate = r'''
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'core/app.dart';
import 'core/config/app_config.dart';
import 'core/app_providers.dart';
import 'core/router/app_router.dart';
import 'core/service_locator.dart';
import 'generated/l10n.dart'; // Generated by `flutter gen-l10n`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load app configuration
  await AppConfig.load();

  // Setup Dependency Injection
  await ServiceLocator.setup();

  runApp(
    MultiProvider(
      providers: AppProviders.providers,
      child: const MainApp(),
    ),
  );
}
''';
